baseURL = "https://werkgroep-toetsen-op-afstand.github.io"
languageCode = "en-us"
title = "Educational Redesign Aid"
theme = "TLC-UvA-theme"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "Educational Redesign Aid"
    weight = 1
  [languages.nl]
    languageName = "Nederlands"
    title = "Educational Redesign Aid"
    weight = 2
