baseURL = "https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/"
publishDir = "docs"
languageCode = "en-us"
title = "Assessment Selection Tool"
theme = "Selection-Theme"
defaultContentLanguage = "nl"

[params]
  landingpageTitle = "Breng je toetsing online"
  landingpageSubtitle = "De werkgroep toetsen op afstand heeft deze keuze tool voor toetsen ontwikkeld. Op basis van jouw onderwijssituatie kom je snel tot de geschikte toetsmethoden."
  landingpageBannerImage = "images/landing-no-logo-2.jpg"
  landingpageLogoImage = "images/toetsendiap.png"
  landingpageLogoImageSmall = "images/toetsendiap.png"

  color = "#9E8E67"

 [languages]
   [languages.en]
     languageName = "English"
     title = "Educational Redesign Aid"
     weight = 2
   [languages.nl]
languageName = "Nederlands"
     title = "Educational Redesign Aid"
     weight = 1
