baseURL = "https://werkgroep-toetsen-op-afstand.github.io/remote-assessment-aid/"
publishDir = "docs"
languageCode = "en-us"
title = "Educational Redesign Aid"
theme = "TLC-UvA-theme"
defaultContentLanguage = "nl"

[params]
  landingpageTitle = "Breng je toetsing online"
  landingpageSubtitle = "De werkgroep toetsen op afstand heeft deze keuze tool voor toetsen ontwikkeld. Op basis van jouw onderwijssituatie kom je snel tot de geschikte toetsmethoden."
  landingpageBannerImage = "images/landing-no-logo.jpg"
  landingpageLogoImage = "images/toetsendiap.png"
  landingpageLogoImageSmall = "images/teaching-centre-hero.png"

  color = "#9E8E67"

# [languages]
#   [languages.en]
#     languageName = "English"
#     title = "Educational Redesign Aid"
#     weight = 1
#   [languages.nl]
#     languageName = "Nederlands"
#     title = "Educational Redesign Aid"
#     weight = 2
