---
title: test
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/_index.md')) ) {
paste(yaml::read_yaml('content/1-on-1/application/_index.md')$title,
yaml::read_yaml('content/1-on-1/application/_index.md')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/_index.md'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/description.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/description.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/description.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/description.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/how.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/how.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/how.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/how.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/methods/_index.md')) ) {
paste(yaml::read_yaml('content/1-on-1/application/methods/_index.md')$title,
yaml::read_yaml('content/1-on-1/application/methods/_index.md')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/methods/_index.md'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/methods/observation.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/methods/observation.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/methods/observation.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/methods/observation.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/methods/oral_exams.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/methods/oral_exams.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/methods/oral_exams.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/methods/oral_exams.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/methods/portfolio.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/methods/portfolio.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/methods/portfolio.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/methods/portfolio.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/methods/project_product.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/methods/project_product.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/methods/project_product.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/methods/project_product.Rmd'}
```
 
---

```{r, warning=FALSE, echo=FALSE, results='asis'}
if(!berryFunctions::is.error(yaml::read_yaml('content/1-on-1/application/tips.Rmd')) ) {
paste(yaml::read_yaml('content/1-on-1/application/tips.Rmd')$title,
yaml::read_yaml('content/1-on-1/application/tips.Rmd')$subtitle) -> title

cat(paste('##', title))
}
```
 
```{r child = 'content/1-on-1/application/tips.Rmd'}
```
 
---

